# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('domicilio', models.TextField()),
            ],
        ),
    ]
